### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by iMark21** [gal-orlanczyk/go-swifty-m3u8#2]
Could you develop a sample project code? Thanks!

**Comment by gal-orlanczyk** [comment]
Hi @iMark21, I will add a sample in the future but for now you can check the unit tests, they pretty much cover most use cases as I wanted them to give me a good indication if something is not working.
Let me know if you are missing a specific use case.

**Comment by iMark21** [comment]
Ok! But would be nice if you can develop an example. Thanks!
